#!/bin/sh /etc/rc.common
# Example script
# Copyright (C) 2007 OpenWrt.org

START=10
STOP=15

start() {
        sh /triangl-package-updater/triangl_keep_running.sh &
        sh /triangl-package-updater/triangl_packet_updater.sh &
}

stop() {
        echo stop
        kill $(ps | grep 'sh /triangl-package-updater/triangl_keep_running.sh' | head -1 | grep -o '[0-9
]* root' | grep -o '[0-9]*')
        kill $(ps | grep 'sh /triangl-package-updater/triangl_packet_updater.sh' | head -1 | grep -o '[0-9]* root' | grep -o '[0-9]*')
        kill $(ps | grep 'rssi-polling' | head -1 | grep -o '[0-9]* root' | grep -o '[0-9]*')
        kill $(ps | grep 'airodump-ng' | head -1 | grep -o '[0-9]* root' | grep -o '[0-9]*')
        # commands to kill application
}
